/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 c:\Users\Théo\Desktop\projet_top1\public\models\low_poly_city.glb -o c:\Users\Théo\Desktop\projet_top1\src\components\game1\Background.jsx 
Author: Igor Tretyakov (https://sketchfab.com/vdv77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-c41536b9f8d24ff1b42656f98be032ba
Title: low poly city
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export const Background = (props) => {
  const { nodes, materials } = useGLTF('/models/low_poly_city.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-450.464, 368.523, 2623.864]}>
        <mesh geometry={nodes['������������_������__13'].geometry} material={materials.material} />
        <mesh geometry={nodes['������������_������_����������������1_13'].geometry} material={materials.material_1} />
        <mesh geometry={nodes['������������_������_����������������11_13'].geometry} material={materials.material_3} />
        <mesh geometry={nodes['������������_������_����������������5_13'].geometry} material={materials.material_4} />
        <mesh geometry={nodes['������������_������_����������������6_13'].geometry} material={materials.material_5} />
        <mesh geometry={nodes['������������_������_����������������17_13'].geometry} material={materials.material_8} />
        <mesh geometry={nodes['������������_������_����������������12_13'].geometry} material={materials.material_6} />
        <mesh geometry={nodes['������������_������_����������������19_13'].geometry} material={materials.material_7} />
        <mesh geometry={nodes['������������_������_����������������_13'].geometry} material={materials.material_11} />
        <mesh geometry={nodes['������������_������_����������������3_13'].geometry} material={materials.material_9} />
        <mesh geometry={nodes['������������_������_����������������2_13'].geometry} material={materials.material_10} />
        <mesh geometry={nodes['������������_������_����������������2_13_1'].geometry} material={materials['.2_0']} />
        <mesh geometry={nodes['������������_������_����������������1_13_1'].geometry} material={materials['.1_0']} />
        <mesh geometry={nodes['������������_������_����������������23_13'].geometry} material={materials.material_27} />
        <mesh geometry={nodes['������������_������_����������������14_13'].geometry} material={materials.material_28} />
        <mesh geometry={nodes['������������_������_����������������43_13'].geometry} material={materials.material_29} />
        <mesh geometry={nodes['������������_������_Background_13'].geometry} material={materials.Background} />
        <mesh geometry={nodes['������������_������_����������������4_13'].geometry} material={materials.material_30} />
        <mesh geometry={nodes['������������_������_����������������9_13'].geometry} material={materials.material_32} />
        <mesh geometry={nodes['������������_������_����������������31_13'].geometry} material={materials.material_33} />
        <mesh geometry={nodes['������������_������_����������������16_13'].geometry} material={materials.material_34} />
        <mesh geometry={nodes['������������_������_����������������38_13'].geometry} material={materials.material_35} />
        <mesh geometry={nodes['������������_������_����������������27_13'].geometry} material={materials.material_36} />
        <mesh geometry={nodes['������������_������_����������������37_13'].geometry} material={materials.material_37} />
        <mesh geometry={nodes['������������_������_����������������30_13'].geometry} material={materials.material_39} />
        <mesh geometry={nodes['������������_������_����������������24_13'].geometry} material={materials.material_40} />
        <mesh geometry={nodes['������������_������_����������������20_13'].geometry} material={materials.material_41} />
        <mesh geometry={nodes['������������_������_����������������7_13'].geometry} material={materials.material_42} />
        <mesh geometry={nodes['������������_������_����������������10_13'].geometry} material={materials.material_13} />
        <mesh geometry={nodes['������������_������_����������������39_13'].geometry} material={materials.material_14} />
        <mesh geometry={nodes['������������_������_����������������8_13'].geometry} material={materials.material_15} />
        <mesh geometry={nodes['������������_������_����������������13_13'].geometry} material={materials.material_16} />
        <mesh geometry={nodes['������������_������_����������������13_13_1'].geometry} material={materials.material_16} />
        <mesh geometry={nodes['������������_������_����������������13_13_2'].geometry} material={materials.material_16} />
        <mesh geometry={nodes['������������_������_����������������35_13'].geometry} material={materials.material_17} />
        <mesh geometry={nodes['������������_������_����������������21_13'].geometry} material={materials.material_18} />
        <mesh geometry={nodes['������������_������_����������������33_13'].geometry} material={materials.material_19} />
        <mesh geometry={nodes['������������_������_����������������1_13_2'].geometry} material={materials['.1_1']} />
        <mesh geometry={nodes['������������_������_����������������36_13'].geometry} material={materials.material_38} />
        <mesh geometry={nodes['������������_������_����������������13_13_3'].geometry} material={materials['.13_0']} />
        <mesh geometry={nodes['������������_������_����������������42_13'].geometry} material={materials.material_23} />
        <mesh geometry={nodes['������������_������_����������������26_13'].geometry} material={materials.material_24} />
        <mesh geometry={nodes['������������_������_����������������29_13'].geometry} material={materials.material_25} />
        <mesh geometry={nodes['������������_������_����������������34_13'].geometry} material={materials.material_26} />
        <mesh geometry={nodes['������������_������_����������������15_13'].geometry} material={materials.material_43} />
        <mesh geometry={nodes['������������_������_����������������18_13'].geometry} material={materials.material_44} />
        <mesh geometry={nodes['������������_������_����������������22_13'].geometry} material={materials.material_45} />
        <mesh geometry={nodes['������������_������_����������������25_13'].geometry} material={materials.material_46} />
        <mesh geometry={nodes['������������_������_����������������25_13_1'].geometry} material={materials.material_46} />
        <mesh geometry={nodes['������������_������_����������������_2'].geometry} material={materials.material_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_city.glb')
