/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 c:\Users\Théo\Desktop\projet_top1\public\models\low_poly_city.glb -o c:\Users\Théo\Desktop\projet_top1\src\components\game1\Background.jsx 
Author: Igor Tretyakov (https://sketchfab.com/vdv77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-c41536b9f8d24ff1b42656f98be032ba
Title: low poly city
*/

import React, {  useRef } from "react";
import {useGLTF} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export const Background2 = (props) => {
  const {scene} = useGLTF("/models/earth(1).glb");
  const ref = useRef()

  useFrame(()=>{
    ref.current.rotation.y += 0.001
  })

  return (
    <group {...props} dispose={null} ref={ref}>
      <primitive object={scene} />
    </group>
  );
};

useGLTF.preload("/models/earth(1).glb");
